import { ArrowRight, Braces, Calculator, CheckCircle2, ListTree, Play, Wrench } from 'lucide-react'

export function Lesson02Opening({ mode, stageNumber, onPrimary, onReview, onSummary }: { mode: 'new' | 'progress' | 'completed'; stageNumber: number; onPrimary: () => void; onReview: () => void; onSummary: () => void }) {
  const steps = [['Create','Build three simple nodes.',Play],['Read','See objects and arrays.',Braces],['Navigate','Follow nested paths.',ListTree],['Calculate','Count items and total prices.',Calculator],['Repair','Fix missing and changed fields.',Wrench]] as const
  return <section className="lesson02-opening"><div className="json-opening-copy"><p className="eyebrow">Lesson 02 · Practical Foundation Lab</p><h1>JSON becomes easy<br/>when you can <strong>see the shape.</strong></h1><p>You will build one small workflow directly in n8n, paste known order data, turn it into five clean fields, test a different order, and repair real shape problems. No Webhook URL. No production connection. No external credential.</p><div className="opening-actions">{mode === 'completed' ? <><button className="button button--primary" onClick={onReview}>Review Lesson 02 <ArrowRight size={17}/></button><button className="button button--light" onClick={onSummary}>Engineering Summary</button></> : <button className="button button--primary" onClick={onPrimary}>{mode === 'progress' ? `Resume Stage ${String(stageNumber).padStart(2,'0')}` : 'Start building in n8n'} <ArrowRight size={17}/></button>}</div></div><div className="json-transform-visual"><div><span>Nested input</span><pre>{`customer { name, country }\norder { id, items[] }`}</pre></div><b>↓ Edit Fields</b><div className="is-clean"><span>Clean output</span><pre>{`customerName\ncustomerCountry\norderId\nitemCount\norderTotal`}</pre></div></div><div className="mission-step-grid">{steps.map(([title,text,Icon])=><article key={title}><Icon size={21}/><strong>{title}</strong><span>{text}</span></article>)}</div><div className="opening-promise"><strong>Build in your n8n</strong><span>DeTLeng gives every exact action and expected result; you perform the real work.</span></div></section>
}

export function Lesson02Completion({ onReview }: { onReview: () => void }) {
  return <div className="lesson02-completion"><section className="completion-hero"><span className="completion-badge"><CheckCircle2 size={17}/> Lesson 02 complete</span><h2>You read the shape.<br/>You transformed the data.<br/><strong>You repaired the failures.</strong></h2><p className="completion-lede">Nested JSON is now something you can work with directly inside n8n.</p></section><div className="json-journey-recap">{['Built the three-node workflow','Read objects and arrays','Mapped five output fields','Proved dynamic totals','Handled missing fields','Exported the workflow'].map((item,index)=><div key={item}><span>{String(index+1).padStart(2,'0')}</span>{item}</div>)}</div><blockquote>JSON is the shape data takes when it travels between systems.</blockquote><div className="mental-model"><span>Shape</span><b>→</b><span>Path</span><b>→</b><span>Value</span><b>→</b><span>Clean output</span></div><section className="next-lesson-card"><p className="eyebrow">Next · Lesson 03</p><h3>REST APIs</h3><p>You can now read the JSON systems send. Next, learn how applications request and exchange that data.</p><a className="button button--primary" href="/lessons/rest-apis">Continue to Lesson 03 <ArrowRight size={17}/></a><button className="button button--light" onClick={onReview}>Review Lesson 02</button></section></div>
}
