import { AlertCircle, ArrowLeft, ArrowRight, Braces, CheckCircle2, Clipboard, Database, LoaderCircle, LogOut, Network, Radio, ShieldCheck, TriangleAlert } from 'lucide-react'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Footer } from '../components/Footer'
import { useAuth } from '../context/AuthContext'
import { callLessonApi } from '../lib/lesson-api'
import { supabase } from '../lib/supabase'
import { Lesson02Completion, Lesson02Opening } from './Lesson02Story'
import { CopyExpression, Lesson02Stage01, Lesson02Stage02, Lesson02Stage03, Lesson02Stage04, Lesson02Stage05, Lesson02Stage06, Lesson02Stage07, StageHeader } from './Lesson02Guidance'
import { lesson02Expressions as expressions } from './lesson02-expressions'
import { advanceLesson02Progress, readLesson02Cache, reconcileLesson02Progress, writeLesson02Cache } from './lesson02-cache'
import { lesson02CanComplete, lesson02InitialProgress, lesson02Stages } from './lesson02-config'
import { computeLesson02Status } from './lesson02-status'
import type { Lesson02Progress } from './lesson02-types'
import { StageIndicator } from './StageIndicator'
import type { LiveResult } from './types'

type Feedback = { passed?: boolean; message: string; learning?: boolean }
const missionViewRequested = () => new URLSearchParams(window.location.search).get('view') === 'mission'
const markPassed = (progress: Lesson02Progress, stage: string) => ({ ...progress.stageStates, [stage]: 'passed' as const })

function FeedbackMessage({ feedback }: { feedback: Feedback }) {
  return <p className={`lab-feedback ${feedback.learning ? 'lab-feedback--learning' : feedback.passed ? 'lab-feedback--pass' : 'lab-feedback--fail'}`} role="status">{feedback.learning ? <TriangleAlert size={20}/> : feedback.passed ? <CheckCircle2 size={20}/> : <AlertCircle size={20}/>} {feedback.message}</p>
}
function ResultCards({ results }: { results: LiveResult[] }) {
  if (!results.length) return null
  return <div className="live-result-grid">{results.map((result) => <article className={result.passed ? 'live-result is-pass' : result.reached ? 'live-result is-learning' : 'live-result is-fail'} key={result.id}><span>{result.passed ? '✓' : result.reached ? '!' : '×'}</span><div><strong>{result.label}</strong><p>{result.message}</p>{result.actual && <small>Received: {JSON.stringify(result.actual)}</small>}</div></article>)}</div>
}

export function Lesson02Lab() {
  const { user, session, logout } = useAuth()
  const [prerequisite, setPrerequisite] = useState<'loading' | 'blocked' | 'ready'>('loading')
  const [progress, setProgress] = useState<Lesson02Progress>(() => user ? readLesson02Cache(user.id)?.progress ?? structuredClone(lesson02InitialProgress) : structuredClone(lesson02InitialProgress))
  const progressRef = useRef(progress); const saveSequenceRef = useRef(0); const startedAtRef = useRef<string | null>(null); const completedAtRef = useRef<string | null>(null)
  const [loading, setLoading] = useState(true); const [saveState, setSaveState] = useState(''); const [syncPending, setSyncPending] = useState(false)
  const [testUrl, setTestUrl] = useState(''); const [productionUrl, setProductionUrl] = useState(''); const [busy, setBusy] = useState('')
  const [feedback, setFeedback] = useState<Feedback | null>(null); const [liveResults, setLiveResults] = useState<LiveResult[]>([]); const [showIntro, setShowIntro] = useState(missionViewRequested)

  const navigateMission = (open: boolean) => { const url = new URL(window.location.href); if (open) url.searchParams.set('view', 'mission'); else url.searchParams.delete('view'); window.history.pushState({}, '', `${url.pathname}${url.search}${url.hash}`); setShowIntro(open) }
  useEffect(() => { progressRef.current = progress }, [progress])

  const persist = useCallback(async (next: Lesson02Progress, complete = false) => {
    if (!user) return false
    const sequence = ++saveSequenceRef.current; const now = new Date().toISOString(); const completedAt = complete || next.completed ? completedAtRef.current ?? now : null
    writeLesson02Cache(user.id, next, true); setSyncPending(true); setSaveState('Saving…')
    const { error } = await supabase.from('lesson_progress').upsert({ user_id: user.id, lesson_id: 2, status: complete ? 'Completed' : computeLesson02Status(next), progress_data: next, current_stage: next.currentStage, started_at: startedAtRef.current ?? now, last_activity_at: now, completed_at: completedAt, updated_at: now }, { onConflict: 'user_id,lesson_id' })
    if (error) { console.error('Lesson 02 sync failed', error); if (sequence === saveSequenceRef.current) setSaveState('Your progress is saved locally and will sync when the connection is restored.'); return false }
    startedAtRef.current ??= now; completedAtRef.current = completedAt
    if (sequence === saveSequenceRef.current && progressRef.current.revision === next.revision) { writeLesson02Cache(user.id, next, false); setSyncPending(false); setSaveState('Progress saved') }
    return true
  }, [user])
  const updateProgress = useCallback((patch: Partial<Lesson02Progress>) => { const next = advanceLesson02Progress(progressRef.current, patch); progressRef.current = next; setProgress(next); if (user) { writeLesson02Cache(user.id, next, true); setSyncPending(true) } void persist(next); return next }, [persist, user])

  useEffect(() => {
    if (!user) return
    const cached = readLesson02Cache(user.id)
    Promise.all([
      supabase.from('lesson_progress').select('status').eq('user_id', user.id).eq('lesson_id', 1).maybeSingle(),
      supabase.from('lesson_progress').select('progress_data,current_stage,started_at,completed_at,updated_at').eq('user_id', user.id).eq('lesson_id', 2).maybeSingle(),
      supabase.from('lesson_connections').select('webhook_url,connection_status').eq('user_id', user.id).eq('lesson_id', 2).maybeSingle(),
    ]).then(([lesson01, current, connection]) => {
      if (lesson01.error || lesson01.data?.status !== 'Completed') { setPrerequisite('blocked'); setLoading(false); return }
      setPrerequisite('ready')
      if (connection.data?.webhook_url) setProductionUrl(connection.data.webhook_url)
      if (current.error) { console.error('Lesson 02 hydration failed', current.error); const fallback = cached?.progress ?? structuredClone(lesson02InitialProgress); progressRef.current = fallback; setProgress(fallback); setShowIntro(missionViewRequested() || fallback.revision === 0); setSyncPending(true); setSaveState('Your progress is saved locally and will sync when the connection is restored.'); setLoading(false); return }
      startedAtRef.current = current.data?.started_at ?? null; completedAtRef.current = current.data?.completed_at ?? null
      const server = current.data ? { ...(current.data.progress_data as object), currentStage: current.data.current_stage, clientUpdatedAt: (current.data.progress_data as { clientUpdatedAt?: string })?.clientUpdatedAt || current.data.updated_at } : null
      const next = current.data ? reconcileLesson02Progress(server, cached) : cached?.progress ?? structuredClone(lesson02InitialProgress)
      progressRef.current = next; setProgress(next); setShowIntro(missionViewRequested() || next.revision === 0 && !next.completed); setLoading(false)
      if (current.data && cached?.syncPending) window.setTimeout(() => void persist(next), 0)
    })
  }, [persist, user])
  useEffect(() => { const retry = () => { if (user && prerequisite === 'ready') void persist(progressRef.current, progressRef.current.completed) }; window.addEventListener('online', retry); return () => window.removeEventListener('online', retry) }, [persist, prerequisite, user])
  useEffect(() => { const syncRoute = () => setShowIntro(missionViewRequested()); window.addEventListener('popstate', syncRoute); return () => window.removeEventListener('popstate', syncRoute) }, [])

  const canComplete = lesson02CanComplete(progress); const status = computeLesson02Status(progress); const stage = progress.viewedStage; const currentIndex = lesson02Stages.findIndex((item) => item.id === stage)
  const canOpenStage = (id: string) => { if (id === 'read-shape') return true; if (id === 'capture-payload') return progress.jsonAnatomyCompleted; if (id === 'nested-fields') return progress.testEventPassed; if (id === 'arrays') return progress.nestedFieldsCompleted; if (id === 'normalizer') return progress.arraysCompleted; if (id === 'publish-connect') return progress.normalizerCompleted; if (id === 'live-challenge') return progress.productionConnected; return id === 'complete' && canComplete }
  const clearStageFeedback = () => { setFeedback(null); setLiveResults([]) }
  const goToStage = (id: string) => { if (!canOpenStage(id)) return; clearStageFeedback(); const target = lesson02Stages.findIndex((item) => item.id === id); const furthest = lesson02Stages.findIndex((item) => item.id === progressRef.current.currentStage); updateProgress({ viewedStage: id, currentStage: target > furthest ? id : progressRef.current.currentStage, lastNeedsAttention: false, stageStates: { ...progressRef.current.stageStates, [id]: progressRef.current.stageStates[id] === 'passed' ? 'passed' : 'in_progress' } }); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const finishStage = (stageId: string, patch: Partial<Lesson02Progress>, nextId: string) => { clearStageFeedback(); return updateProgress({ ...patch, viewedStage: nextId, currentStage: nextId, stageStates: { ...markPassed(progressRef.current, stageId), [nextId]: 'in_progress' } }) }
  async function runApi(action: string, path: string, webhookUrl: string) { setBusy(action); setFeedback(null); try { return await callLessonApi(path, session, { webhookUrl }) } catch (error) { setFeedback({ passed: false, message: error instanceof Error ? error.message : 'The live test could not be completed.' }); return null } finally { setBusy('') } }
  async function sendTestEvent() { const result = await runApi('test-event', '/api/lessons/json/test-event', testUrl); if (!result) return; setFeedback({ passed: result.passed, message: result.message || 'Detleng sent the nested order.' }); updateProgress({ testEventPassed: result.passed, lastNeedsAttention: !result.passed, stageStates: { ...progress.stageStates, 'capture-payload': result.passed ? 'passed' : 'needs_attention' } }) }
  async function connectProduction() { const result = await runApi('connect', '/api/lessons/json/connect', productionUrl); if (!result) return; setLiveResults(result.results ?? []); if (!result.passed) { setFeedback({ passed: false, message: result.message || 'The workflow responded, but its normalized output is not ready yet.' }); updateProgress({ lastNeedsAttention: true }); return } const now = new Date().toISOString(); const { error } = await supabase.from('lesson_connections').upsert({ user_id: user!.id, lesson_id: 2, webhook_url: productionUrl, connection_status: 'valid', last_tested_at: now, updated_at: now }, { onConflict: 'user_id,lesson_id' }); if (error) { console.error('Lesson 02 connection save failed', error); setFeedback({ passed: false, message: 'The workflow passed, but Detleng could not save the private connection. Please retry.' }); return } setFeedback({ passed: true, message: 'Production JSON normalizer connected and verified.' }); updateProgress({ productionConnected: true, lastNeedsAttention: false, stageStates: markPassed(progressRef.current, 'publish-connect') }) }
  async function runChallenge(mode: 'live' | 'break' | 'repair') { const path = `/api/lessons/json/${mode === 'live' ? 'live-test' : mode === 'break' ? 'break-test' : 'repair-test'}`; const result = await runApi(mode, path, productionUrl); if (!result) return; setLiveResults(result.results ?? []); if (mode === 'break') { const observed = result.passed && result.reached; setFeedback({ passed: observed, learning: observed, message: observed ? 'Schema drift detected exactly as intended. The data exists; the saved path is now wrong.' : result.reached ? 'The changed schema still passed. Confirm the normalizer only reads customer.name before trying again.' : 'Detleng could not reach the workflow. Network failure does not count as schema-drift evidence.' }); updateProgress({ schemaDriftObserved: Boolean(observed), lastNeedsAttention: !result.reached, stageStates: { ...progressRef.current.stageStates, 'live-challenge': 'in_progress' } }); return } if (mode === 'repair') { setFeedback({ passed: result.passed, message: result.passed ? 'Repair verified. Original and changed customer shapes both work.' : 'The repair must support both customer.name and customer.fullName.' }); updateProgress({ repairPassed: result.passed, lastNeedsAttention: !result.passed, stageStates: { ...progressRef.current.stageStates, 'live-challenge': result.passed ? 'passed' : 'needs_attention' } }); return } const find = (id: string) => result.results?.find((item) => item.id === id)?.passed === true; setFeedback({ passed: result.passed, message: result.passed ? 'All three JSON contracts passed.' : 'One JSON contract needs attention. Open its result below and compare the expected shape.' }); updateProgress({ normalCasePassed: find('normal'), variableItemsPassed: find('variable-items'), missingCountryPassed: find('missing-country'), lastNeedsAttention: !result.passed, stageStates: { ...progressRef.current.stageStates, 'live-challenge': result.passed ? 'in_progress' : 'needs_attention' } }) }
  async function completeLesson() { if (!lesson02CanComplete(progressRef.current)) return; const next = advanceLesson02Progress(progressRef.current, { completed: true, currentStage: 'complete', viewedStage: 'complete', lastNeedsAttention: false, stageStates: markPassed(progressRef.current, 'complete') }); if (await persist(next, true)) { progressRef.current = next; setProgress(next); setSaveState('Lesson 02 completed. Your dashboard is updated.') } }

  const completionItems = useMemo(() => [['Read JSON anatomy',progress.jsonAnatomyCompleted],['Captured a real nested payload',progress.testEventPassed],['Mapped nested fields',progress.nestedFieldsCompleted],['Explored arrays',progress.arraysCompleted],['Built the normalizer',progress.normalizerCompleted],['Connected production workflow',progress.productionConnected],['Passed three live cases',progress.normalCasePassed&&progress.variableItemsPassed&&progress.missingCountryPassed],['Observed schema drift',progress.schemaDriftObserved],['Verified old + new schemas',progress.repairPassed]] as const,[progress])
  if (loading || prerequisite === 'loading') return <main className="route-loading"><p>Loading Lesson 02…</p></main>
  if (prerequisite === 'blocked') return <div className="portal-page"><header className="portal-header"><a className="back-link" href="/dashboard"><ArrowLeft size={18}/> Dashboard</a><a className="brand brand--compact" href="/"><span className="brand-mark"><Network size={19}/></span><span>n8n <strong>Detleng</strong></span></a></header><main className="portal-main prerequisite-shell"><div className="prerequisite-card"><ShieldCheck size={42}/><p className="eyebrow">Lesson 02 prerequisite</p><h1>Build the workflow foundation first.</h1><p>Complete Lesson 01 first so you already understand workflows, nodes and Webhooks.</p><a className="button button--primary" href="/lessons/n8n-core">Open Lesson 01 <ArrowRight size={17}/></a><small>No Lesson 02 progress has been created.</small></div></main><Footer/></div>
  const openingMode = progress.completed ? 'completed' : progress.revision > 0 ? 'progress' : 'new'
  if (!showIntro && stage !== 'complete') {
    const guidedStage = <>
      {stage === 'read-shape' && <Lesson02Stage01 onContinue={() => finishStage('read-shape', { jsonAnatomyCompleted: true }, 'capture-payload')}/>}
      {stage === 'capture-payload' && <Lesson02Stage02 testUrl={testUrl} setTestUrl={setTestUrl} busy={busy === 'test-event'} passed={progress.testEventPassed} feedback={feedback && <FeedbackMessage feedback={feedback}/>} onSend={() => void sendTestEvent()} onContinue={() => finishStage('capture-payload', { testEventPassed: true }, 'nested-fields')}/>}
      {stage === 'nested-fields' && <Lesson02Stage03 onContinue={() => finishStage('nested-fields', { nestedFieldsCompleted: true }, 'arrays')}/>}
      {stage === 'arrays' && <Lesson02Stage04 onContinue={() => finishStage('arrays', { arraysCompleted: true }, 'normalizer')}/>}
      {stage === 'normalizer' && <Lesson02Stage05 onContinue={() => finishStage('normalizer', { normalizerCompleted: true }, 'publish-connect')}/>}
      {stage === 'publish-connect' && <Lesson02Stage06 productionUrl={productionUrl} setProductionUrl={setProductionUrl} busy={busy === 'connect'} connected={progress.productionConnected} feedback={feedback && <FeedbackMessage feedback={feedback}/>} results={<ResultCards results={liveResults}/>} onConnect={() => void connectProduction()} onContinue={() => goToStage('live-challenge')}/>}
      {stage === 'live-challenge' && <Lesson02Stage07 livePassed={progress.normalCasePassed && progress.variableItemsPassed && progress.missingCountryPassed} schemaDriftObserved={progress.schemaDriftObserved} repairPassed={progress.repairPassed} busy={busy} feedback={feedback && <FeedbackMessage feedback={feedback}/>} results={<ResultCards results={liveResults}/>} canComplete={lesson02CanComplete(progress)} onLive={() => void runChallenge('live')} onBreak={() => void runChallenge('break')} onRepair={() => void runChallenge('repair')} onComplete={() => goToStage('complete')}/>}
    </>
    return <div className="portal-page"><header className="portal-header"><a className="back-link" href="/dashboard"><ArrowLeft size={18}/> Dashboard</a><div className="portal-header-actions"><a className="brand brand--compact" href="/"><span className="brand-mark"><Network size={19}/></span><span>n8n <strong>Detleng</strong></span></a><button className="button button--ghost" onClick={() => void logout()}><LogOut size={17}/> Log out</button></div></header><main className="portal-main lab-shell lesson02-shell"><div className="lab-hero"><div><p className="eyebrow">Lesson 02 · Live Foundation Lab</p><h1>JSON</h1><p className="portal-lede">Read, navigate and reshape the language your automations speak.</p></div><div className="lab-hero-side"><div className={`lab-status lab-status--${status.toLowerCase().replaceAll(' ', '-')}`}><span>Automatic status</span><strong>{status}</strong><small>{saveState || 'Progress syncs to your learner account.'}</small>{syncPending && <button className="sync-retry" onClick={() => void persist(progressRef.current, progressRef.current.completed)}>Retry sync</button>}</div><button className="button button--light lesson-opening-link" onClick={() => navigateMission(true)}>View lesson mission</button></div></div><div className="lab-reminder"><strong>Read in Detleng. Transform in your n8n.</strong><span>Your workflow and credentials remain yours.</span></div><StageIndicator stages={lesson02Stages} current={stage} states={progress.stageStates} onSelect={goToStage} isEnabled={canOpenStage}/><section className="lab-panel lesson02-panel">{guidedStage}</section><div className="lab-controls"><button className="button button--light" disabled={currentIndex <= 0} onClick={() => goToStage(lesson02Stages[currentIndex - 1]?.id)}>Previous</button><span>Stage {currentIndex + 1} of {lesson02Stages.length}</span><button className="button button--light" disabled={currentIndex >= lesson02Stages.length - 1 || !canOpenStage(lesson02Stages[currentIndex + 1]?.id)} onClick={() => goToStage(lesson02Stages[currentIndex + 1]?.id)}>Next</button></div></main><Footer/></div>
  }
  return <div className="portal-page"><header className="portal-header"><a className="back-link" href="/dashboard"><ArrowLeft size={18}/> Dashboard</a><div className="portal-header-actions"><a className="brand brand--compact" href="/"><span className="brand-mark"><Network size={19}/></span><span>n8n <strong>Detleng</strong></span></a><button className="button button--ghost" onClick={() => void logout()}><LogOut size={17}/> Log out</button></div></header><main className="portal-main lab-shell lesson02-shell">{showIntro ? <Lesson02Opening mode={openingMode} stageNumber={Math.max(1, lesson02Stages.findIndex((item) => item.id === progress.currentStage) + 1)} onPrimary={() => { navigateMission(false); if (progress.revision === 0) updateProgress({ currentStage: 'read-shape', viewedStage: 'read-shape' }) }} onReview={() => { navigateMission(false); goToStage('read-shape') }} onSummary={() => { navigateMission(false); goToStage('complete') }}/> : <><div className="lab-hero"><div><p className="eyebrow">Lesson 02 · Live Foundation Lab</p><h1>JSON</h1><p className="portal-lede">Read, navigate and reshape the language your automations speak.</p></div><div className="lab-hero-side"><div className={`lab-status lab-status--${status.toLowerCase().replaceAll(' ','-')}`}><span>Automatic status</span><strong>{status}</strong><small>{saveState || 'Progress syncs to your learner account.'}</small>{syncPending&&<button className="sync-retry" onClick={() => void persist(progressRef.current,progressRef.current.completed)}>Retry sync</button>}</div><button className="button button--light lesson-opening-link" onClick={() => navigateMission(true)}>View lesson mission</button></div></div><div className="lab-reminder"><strong>Read in Detleng. Transform in your n8n.</strong><span>Your workflow and credentials remain yours.</span></div><StageIndicator stages={lesson02Stages} current={stage} states={progress.stageStates} onSelect={goToStage} isEnabled={canOpenStage}/><section className="lab-panel lesson02-panel">
    {stage==='read-shape'&&<><StageHeader number="01" title="Meet real JSON" text="See structure first. Syntax becomes easier when every shape has a job."/><div className="json-anatomy"><div className="json-tree"><div><span className="type-badge object">Object</span><b>customer</b><div><span className="type-badge string">String</span><code>name: "Ali Khan"</code></div><div><span className="type-badge string">String</span><code>country: "ES"</code></div></div><div><span className="type-badge object">Object</span><b>order</b><div><span className="type-badge string">String</span><code>id: "ORD-101"</code></div><div><span className="type-badge array">Array · 2 items</span><b>items[]</b><div><span className="type-badge object">Object · index 0</span><code>Keyboard · qty 2 · price 50</code></div><div><span className="type-badge object">Object · index 1</span><code>Mouse · qty 1 · price 25</code></div></div></div></div><div className="path-examples"><article><span>Path</span><code>customer.name</code><p>Follow customer, then name.</p></article><article><span>Path</span><code>order.items[0].price</code><p>First array item, then its price.</p></article></div><div className="null-missing"><article><strong>null</strong><p>The field exists, but has no value.</p></article><b>≠</b><article><strong>missing</strong><p>The field does not exist at all.</p></article></div><button className="button button--primary" onClick={() => finishStage('read-shape',{jsonAnatomyCompleted:true},'capture-payload')}>I can read the shape <ArrowRight size={17}/></button></div></>}
    {stage==='capture-payload'&&<><StageHeader number="02" title="Let Detleng send the JSON" text="Capture a real nested order through your n8n Test Webhook."/><div className="workflow-strip"><span>Detleng sample</span><b>→</b><span>Test Webhook</span><b>→</b><span>Your n8n canvas</span></div><ol className="build-steps"><li>Create a workflow named <strong>Detleng Lesson 02 — Order Payload Normalizer</strong>.</li><li>Add a <strong>Webhook</strong> trigger and choose <strong>POST</strong>.</li><li>Open its Test URL and start listening for a test event.</li><li>Paste the temporary Test URL below. It is used once and never saved.</li></ol><label className="url-field"><span>n8n Test Webhook URL</span><input value={testUrl} onChange={(event)=>setTestUrl(event.target.value)} placeholder="https://…app.n8n.cloud/webhook-test/…"/></label><button className="button button--primary" disabled={!testUrl||busy==='test-event'} onClick={()=>void sendTestEvent()}>{busy==='test-event'?<LoaderCircle className="spin" size={17}/>:<Radio size={17}/>} Send Sample Order</button>{feedback&&<FeedbackMessage feedback={feedback}/>}<button className="button button--secondary" disabled={!progress.testEventPassed} onClick={()=>finishStage('capture-payload',{testEventPassed:true},'nested-fields')}>Continue to nested fields <ArrowRight size={17}/></button></>}
    {stage==='nested-fields'&&<><StageHeader number="03" title="Turn paths into values" text="Map values from the Webhook body into fields with stable names."/><p className="lab-tip"><Braces size={19}/> n8n Webhook POST data is normally available under <code>$json.body</code>. You can also drag values from the INPUT pane into Edit Fields to let n8n generate paths.</p><div className="breadcrumb-path"><span>$json</span><b>›</b><span>body</span><b>›</b><span>customer</span><b>›</b><strong>name</strong></div><div className="expression-list"><CopyExpression label="customerName" value={expressions.name}/><CopyExpression label="customerCountry" value={expressions.country}/><CopyExpression label="orderId" value={expressions.id}/></div><div className="contract-note"><strong>Predictable contract</strong><p>If country is missing, the output still contains <code>customerCountry</code>, with the value <code>null</code>.</p></div><button className="button button--primary" onClick={()=>finishStage('nested-fields',{nestedFieldsCompleted:true},'arrays')}>My nested fields are mapped <ArrowRight size={17}/></button></>}
    {stage==='arrays'&&<><StageHeader number="04" title="One order. Many items." text="An array is an ordered list. Its first position is index zero."/><div className="array-visual"><article><span>items[0]</span><strong>Keyboard</strong><small>2 × 50</small></article><article><span>items[1]</span><strong>Mouse</strong><small>1 × 25</small></article><div className="index-rule"><b>0</b> first <b>1</b> second <b>2</b> third</div></div><CopyExpression label="Inspect the first item name" value="{{ $json.body.order.items[0].name }}"/><div className="exploration-card"><Clipboard size={24}/><div><strong>Array exploration · Split Out</strong><p>Add Split Out temporarily or on a side branch and split <code>body.order.items</code>. Inspect how each array object becomes its own n8n item, then return to the direct normalization path. You do not need to keep Split Out in the final workflow.</p></div></div><button className="button button--primary" onClick={()=>finishStage('arrays',{arraysCompleted:true},'normalizer')}>I explored the array <ArrowRight size={17}/></button></>}
    {stage==='normalizer'&&<><StageHeader number="05" title="Turn nested JSON into a clean contract" text="Create one predictable result without hard-coding the number of items."/><div className="output-contract"><p className="eyebrow">Your workflow must return</p>{[['customerName','string'],['customerCountry','string or null'],['orderId','string'],['itemCount','number of line items'],['orderTotal','number']].map(([key,type])=><div key={key}><code>{key}</code><span>{type}</span></div>)}</div><div className="calculation-story"><article><strong>Keyboard</strong><span>2 × 50 = 100</span></article><article><strong>Mouse</strong><span>1 × 25 = 25</span></article><b>Total = 125</b></div><div className="expression-list"><CopyExpression label="itemCount" value={expressions.count}/><CopyExpression label="orderTotal" value={expressions.total}/></div><p className="lab-tip"><Database size={19}/><strong>itemCount is 2</strong> because there are two line-item objects. It is not 3—the total quantity of units.</p><button className="button button--primary" onClick={()=>finishStage('normalizer',{normalizerCompleted:true},'publish-connect')}>My normalizer returns the contract <ArrowRight size={17}/></button></>}
    {stage==='publish-connect'&&<><StageHeader number="06" title="Put your JSON normalizer live" text="Publish the workflow and let Detleng verify its production response."/><ol className="build-steps"><li>Ensure the Webhook accepts POST requests.</li><li>Return the final Normalize Order output from the workflow.</li><li>Publish or activate the workflow.</li><li>Copy the Production URL—not the temporary Test URL.</li></ol><label className="url-field"><span>n8n Production Webhook URL</span><input value={productionUrl} onChange={(event)=>setProductionUrl(event.target.value)} placeholder="https://…app.n8n.cloud/webhook/…"/></label><button className="button button--primary" disabled={!productionUrl||busy==='connect'} onClick={()=>void connectProduction()}>{busy==='connect'?<LoaderCircle className="spin" size={17}/>:<Network size={17}/>} Connect My Workflow</button>{feedback&&<FeedbackMessage feedback={feedback}/>}<ResultCards results={liveResults}/><button className="button button--secondary" disabled={!progress.productionConnected} onClick={()=>goToStage('live-challenge')}>Open the live JSON challenge <ArrowRight size={17}/></button></>}
    {stage==='live-challenge'&&<><StageHeader number="07" title="Live JSON challenge" text="Prove the workflow handles changing data, then experience and repair schema drift."/><div className="challenge-phase"><span>A</span><div><h3>Run three live contracts</h3><p>Detleng sends a normal order, a three-item order and an order with no country.</p><button className="button button--primary" disabled={busy==='live'} onClick={()=>void runChallenge('live')}>Run JSON Live Tests</button></div></div><ResultCards results={liveResults}/>{feedback&&<FeedbackMessage feedback={feedback}/>}<div className="challenge-phase is-break"><span>B</span><div><h3>Now the JSON changes underneath you</h3><p>Detleng changes <code>customer.name</code> to <code>customer.fullName</code>. Your old path should fail logically while the webhook remains reachable.</p><button className="button button--warning" disabled={!progress.normalCasePassed||!progress.variableItemsPassed||!progress.missingCountryPassed||busy==='break'} onClick={()=>void runChallenge('break')}>Detect Schema Drift</button></div></div>{progress.schemaDriftObserved&&<div className="schema-drift-map"><div><small>Old shape</small><code>customer.name</code></div><b>→</b><div><small>New shape</small><code>customer.fullName</code></div><p>The data exists. Your path is wrong.</p></div>}{progress.schemaDriftObserved&&<div className="challenge-phase is-repair"><span>C</span><div><h3>Repair both shapes</h3><p>Update <code>customerName</code> with a fallback, publish again, then verify both the original and changed schema.</p><CopyExpression label="customerName fallback" value={expressions.fallback}/><button className="button button--primary" disabled={busy==='repair'} onClick={()=>void runChallenge('repair')}>Verify Repair</button></div></div>}<details className="watch-card"><summary>Watch for this: items is an object, not an array</summary><pre>{`"items": { "name": "Keyboard", "qty": 2, "price": 50 }`}</pre><p>Your workflow expects an array. This shape is invalid. Recognizing the mismatch is the first step toward defensive data handling; Lesson 16 formalizes resilience.</p></details><button className="button button--secondary" disabled={!lesson02CanComplete(progress)} onClick={()=>goToStage('complete')}>Open completion summary <ArrowRight size={17}/></button></>}
    {stage==='complete'&&<>{progress.completed?<Lesson02Completion onReview={()=>goToStage('read-shape')}/>:<><StageHeader number="08" title="Complete Lesson 02" text="Completion unlocks only after the complete live test, schema drift and repair cycle."/><div className="completion-grid">{completionItems.map(([label,passed])=><div className={passed?'completion-item is-pass':'completion-item'} key={label}><span>{passed?'✓':'○'}</span>{label}</div>)}</div><button className="button button--primary complete-button" disabled={!canComplete} onClick={()=>void completeLesson()}>{canComplete?'Complete Lesson 02':'Complete the JSON lab first'}</button></>}</>}
  </section><div className="lab-controls"><button className="button button--light" disabled={currentIndex<=0} onClick={()=>goToStage(lesson02Stages[currentIndex-1]?.id)}>Previous</button><span>Stage {currentIndex+1} of {lesson02Stages.length}</span><button className="button button--light" disabled={currentIndex>=lesson02Stages.length-1||!canOpenStage(lesson02Stages[currentIndex+1]?.id)} onClick={()=>goToStage(lesson02Stages[currentIndex+1]?.id)}>Next</button></div></>}</main><Footer/></div>
}
